export {default as Home} from './Home'
export {default as About} from './About'
export {default as Profile} from './Profile'
export {default as Library} from './Library'
export {default as Admin} from './Admin'